### ISSUE TITLE
UI indicator for backend connection status

### ISSUE THREAD

**Issue by pl9ed** [smilevideo/Didi-Shou-Chang#48]
Build/deploy takes a few minutes when we spin up the EC2 instance, but the front end is hosted statically on S3 and is always available. We need some kind of indicator or UI view that lets us know the backend isn't ready yet.

The front end actually takes the longest to build and deploy, 

In terms of order of execution it's roughly (although not always)
1. EC2 instance starts
2. Jenkins instance started
3. Docker instance started
4. Startup script runs
5. Jenkins builds triggered
6. WSS server finishes building/deploying
7. S3 server finishes building/deploying
8. Front end finishes building/deploy <-- this step takes a few minutes longer than the rest

It might make more sense to have this on the initial page rather than the lobby. 

![image](https://user-images.githubusercontent.com/9086453/164616144-792f3f7f-7411-4699-b351-8c8647b531cf.png)

We can either prevent joining the lobby altogether, or do it in stages by:
1. Allow joining lobbies with username when WSS is ready (i.e. we can connect to `ws://{EC2_IP}:3030`)
4. Allow uploads when S3 client is ready (i.e. we can connect to `http://{EC2_IP}:8089/tubalub`)

**Comment by smilevideo** [comment]
Solved by https://github.com/smilevideo/Didi-Shou-Chang/commit/7b5840bc4c0490ac62528e1832035f48602a734d
